num1 = int(input("Enter a num1: "))
num2 = int(input("Enter a num2: "))
print("Maximum of " f"{num1, num2} is {max(num1, num2)}")
print("power of " f"{num1, num2} is {pow(num1, num2)}")
print("sum of " f"{num1, num2} is {(num1 + num2)}")
print("Subtraction of " f"{num1, num2} is {(num1 - num2)}")
print("Multiply of " f"{num1, num2} is {(num1 * num2)}")
print("Division of " f"{num1, num2} is {(num1 / num2)}")